# Generated by Django 4.2.4 on 2023-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlığı')),
                ('alignment', models.IntegerField(blank=True, null=True, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Menüler',
                'verbose_name_plural': 'Menüler',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlığı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='İmage', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
