# Generated by Django 4.2.4 on 2023-10-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Menü Başlığı'),
        ),
    ]
