# Generated by Django 4.2.4 on 2023-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_skills'),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='slayt_skill',
            field=models.ManyToManyField(to='about.skills'),
        ),
    ]
