# Generated by Django 4.2.4 on 2023-11-04 16:32

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_mainpage_slayt_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('count', models.IntegerField()),
                ('oid', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='mainpage',
            name='contact_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İletişim Metni'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='contact_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
