# Generated by Django 4.2.4 on 2023-11-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_counter_mainpage_contact_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='contact_counter',
            field=models.ManyToManyField(to='mainpage.counter'),
        ),
    ]
