# Generated by Django 4.2.4 on 2023-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('start_year', models.CharField(max_length=200)),
                ('finish_year', models.CharField(max_length=200)),
            ],
        ),
    ]
